apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-auth-db
  template:
    metadata:
      labels:
        app: pokemon-auth-db
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: "bbchang"
        - name: POSTGRES_PASSWORD
          value: "changemeinprod!"
        - name: POSTGRES_DB
          value: "pokemontest"
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U bbchang -d pokemontest
          initialDelaySeconds: 10 # Increase if your database needs more time to start
          timeoutSeconds: 10      # Increase this to give the probe more time to complete
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-auth-db-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: pokemon-auth-db
  type: ClusterIP